"""PDF Report Generator — weekly ad performance reports."""

from __future__ import annotations

import logging
from datetime import date
from pathlib import Path

logger = logging.getLogger(__name__)
REPORTS_DIR = Path("/Users/oguzkullelioglu/Desktop/ai-cmo-os 2/storage/reports")
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


class ReportGenerator:
    def generate_weekly_pdf(self, report_data: dict, workspace_name: str = "Growth") -> str:
        try:
            from reportlab.lib import colors
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
            from reportlab.lib.units import inch
            from reportlab.platypus import (
                Paragraph,
                SimpleDocTemplate,
                Spacer,
                Table,
                TableStyle,
            )
        except ImportError:
            logger.warning("reportlab not installed — PDF generation skipped")
            return ""

        fname = REPORTS_DIR / f"weekly_{date.today().strftime('%Y%m%d')}.pdf"
        doc = SimpleDocTemplate(str(fname), pagesize=A4)
        styles = getSampleStyleSheet()
        story: list = []

        title_style = ParagraphStyle(
            "T",
            parent=styles["Heading1"],
            fontSize=22,
            textColor=colors.HexColor("#4F46E5"),
        )
        story.append(Paragraph("Weekly Ad Performance Report", title_style))
        story.append(Paragraph(f"{workspace_name} — {date.today()}", styles["Normal"]))
        story.append(Spacer(1, 0.3 * inch))

        kpis = report_data.get("data", {}) or {}
        table_data = [
            ["Metric", "This Week", ""],
            [
                "Total Spend",
                f"${float(kpis.get('total_spend_7d', 0) or 0):,.0f}",
                "",
            ],
            [
                "Total Revenue",
                f"${float(kpis.get('total_revenue_7d', 0) or 0):,.0f}",
                "",
            ],
            [
                "Overall ROAS",
                f"{float(kpis.get('overall_roas_7d', 0) or 0):.2f}x",
                "",
            ],
            [
                "Conversions",
                f"{float(kpis.get('total_conversions_7d', 0) or 0):,.0f}",
                "",
            ],
        ]
        t = Table(table_data, colWidths=[2.5 * inch, 2 * inch, 2 * inch])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4F46E5")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    (
                        "ROWBACKGROUNDS",
                        (0, 1),
                        (-1, -1),
                        [colors.white, colors.HexColor("#F9FAFB")],
                    ),
                ]
            )
        )
        story.append(t)
        story.append(Spacer(1, 0.3 * inch))

        if report_data.get("report"):
            story.append(Paragraph("AI Performance Analysis", styles["Heading2"]))
            for para in str(report_data["report"]).split("\n\n"):
                if para.strip():
                    story.append(Paragraph(para.strip(), styles["Normal"]))
                    story.append(Spacer(1, 0.1 * inch))

        story.append(Spacer(1, 0.5 * inch))
        footer = ParagraphStyle("F", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
        story.append(Paragraph("Generated by AI Growth OS. AI estimates only.", footer))

        doc.build(story)
        return str(fname)
