"""
Country Tax Database — static tax data for 20 countries.

Turkey + all major European countries. Used as a baseline for AI-powered
tax analysis; the AI supplements with contextual knowledge for edge cases.
"""

from __future__ import annotations

COUNTRY_TAX_DATA: dict[str, dict] = {
    "TR": {
        "name": "Turkey",
        "currency": "TRY",
        "vat_name": "KDV (Katma Değer Vergisi)",
        "vat_rates": {"standard": 20.0, "reduced": 10.0, "super_reduced": 1.0},
        "corporate_tax_rate": 25.0,
        "vat_filing": "monthly",
        "vat_deadline_days": 28,
        "tax_authority": "Gelir İdaresi Başkanlığı (GİB)",
        "tax_portal": "https://intvrg.gib.gov.tr",
        "tax_portal_name": "GİB İnteraktif Vergi Dairesi",
        "efatura_portal": "https://efatura.gov.tr",
        "company_types": ["limited", "anonim", "sahis", "kolektif", "komandit"],
        "applicable_taxes": [
            "kdv",
            "kurumlar_vergisi",
            "gecici_vergi",
            "stopaj",
            "damga_vergisi",
            "sgk",
        ],
        "tax_year": "calendar",
        "notes": "KDV beyannamesi her ayın 28'ine kadar verilir. Geçici vergi 3 ayda bir ödenir.",
        "language": "tr",
    },
    "DE": {
        "name": "Germany",
        "currency": "EUR",
        "vat_name": "Umsatzsteuer (USt) / Mehrwertsteuer (MwSt)",
        "vat_rates": {"standard": 19.0, "reduced": 7.0},
        "corporate_tax_rate": 15.0,
        "effective_corporate_rate": 30.0,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 10,
        "tax_authority": "Finanzamt",
        "tax_portal": "https://www.elster.de",
        "tax_portal_name": "ELSTER — Elektronische Steuererklärung",
        "company_types": ["gmbh", "ag", "einzelunternehmen", "ohg", "kg", "ug"],
        "applicable_taxes": [
            "umsatzsteuer",
            "koerperschaftsteuer",
            "gewerbesteuer",
            "einkommensteuer",
            "solidaritaetszuschlag",
            "sozialversicherung",
        ],
        "tax_year": "calendar",
        "notes": "Umsatzsteuervoranmeldung monatlich oder vierteljährlich. ELSTER für elektronische Einreichung.",
        "language": "de",
    },
    "FR": {
        "name": "France",
        "currency": "EUR",
        "vat_name": "TVA (Taxe sur la Valeur Ajoutée)",
        "vat_rates": {"standard": 20.0, "intermediate": 10.0, "reduced": 5.5, "super_reduced": 2.1},
        "corporate_tax_rate": 25.0,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 19,
        "tax_authority": "Direction Générale des Finances Publiques (DGFiP)",
        "tax_portal": "https://www.impots.gouv.fr",
        "tax_portal_name": "impots.gouv.fr — Espace Professionnel",
        "company_types": ["sarl", "sas", "sa", "ei", "eurl", "snc"],
        "applicable_taxes": ["tva", "is", "ir", "cfe", "cvae", "cotisations_sociales"],
        "tax_year": "calendar",
        "language": "fr",
    },
    "IT": {
        "name": "Italy",
        "currency": "EUR",
        "vat_name": "IVA (Imposta sul Valore Aggiunto)",
        "vat_rates": {"standard": 22.0, "reduced": 10.0, "super_reduced": 5.0, "minimum": 4.0},
        "corporate_tax_rate": 24.0,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 16,
        "tax_authority": "Agenzia delle Entrate",
        "tax_portal": "https://www.agenziaentrate.gov.it",
        "tax_portal_name": "Agenzia delle Entrate — Cassetto Fiscale",
        "company_types": ["srl", "spa", "snc", "sas", "ditta_individuale"],
        "applicable_taxes": ["iva", "ires", "irap", "irpef", "contributi_inps"],
        "tax_year": "calendar",
        "language": "it",
    },
    "ES": {
        "name": "Spain",
        "currency": "EUR",
        "vat_name": "IVA (Impuesto sobre el Valor Añadido)",
        "vat_rates": {"standard": 21.0, "reduced": 10.0, "super_reduced": 4.0},
        "corporate_tax_rate": 25.0,
        "vat_filing": "quarterly",
        "vat_deadline_days": 20,
        "tax_authority": "Agencia Tributaria (AEAT)",
        "tax_portal": "https://sede.agenciatributaria.gob.es",
        "tax_portal_name": "Sede Electrónica — Agencia Tributaria",
        "company_types": ["sl", "sa", "autonomo", "cb", "sc"],
        "applicable_taxes": ["iva", "is", "irpf", "seguridad_social"],
        "tax_year": "calendar",
        "language": "es",
    },
    "NL": {
        "name": "Netherlands",
        "currency": "EUR",
        "vat_name": "BTW (Belasting over de Toegevoegde Waarde)",
        "vat_rates": {"standard": 21.0, "reduced": 9.0},
        "corporate_tax_rate": 19.0,
        "vat_filing": "quarterly",
        "vat_deadline_days": 31,
        "tax_authority": "Belastingdienst",
        "tax_portal": "https://www.belastingdienst.nl",
        "tax_portal_name": "Mijn Belastingdienst Zakelijk",
        "company_types": ["bv", "nv", "vof", "eenmanszaak", "cv"],
        "applicable_taxes": ["btw", "vpb", "ib", "loonbelasting"],
        "tax_year": "calendar",
        "language": "nl",
    },
    "GB": {
        "name": "United Kingdom",
        "currency": "GBP",
        "vat_name": "VAT (Value Added Tax)",
        "vat_rates": {"standard": 20.0, "reduced": 5.0, "zero": 0.0},
        "corporate_tax_rate": 25.0,
        "vat_filing": "quarterly",
        "vat_deadline_days": 37,
        "tax_authority": "HM Revenue & Customs (HMRC)",
        "tax_portal": "https://www.gov.uk/business-tax-account",
        "tax_portal_name": "HMRC Business Tax Account",
        "company_types": ["ltd", "plc", "llp", "sole_trader", "partnership"],
        "applicable_taxes": ["vat", "corporation_tax", "paye", "national_insurance"],
        "tax_year": "april_to_march",
        "language": "en",
    },
    "BE": {
        "name": "Belgium",
        "currency": "EUR",
        "vat_name": "TVA/BTW",
        "vat_rates": {"standard": 21.0, "reduced": 12.0, "super_reduced": 6.0},
        "corporate_tax_rate": 25.0,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 20,
        "tax_authority": "SPF Finances / FOD Financiën",
        "tax_portal": "https://finances.belgium.be",
        "tax_portal_name": "MyMinfin Pro",
        "company_types": ["bv", "nv", "vof", "eenmanszaak"],
        "applicable_taxes": ["tva_btw", "isoc", "ipm", "onss_rsz"],
        "tax_year": "calendar",
        "language": "nl_fr",
    },
    "PL": {
        "name": "Poland",
        "currency": "PLN",
        "vat_name": "VAT (Podatek od Towarów i Usług)",
        "vat_rates": {"standard": 23.0, "reduced": 8.0, "super_reduced": 5.0},
        "corporate_tax_rate": 19.0,
        "vat_filing": "monthly",
        "vat_deadline_days": 25,
        "tax_authority": "Krajowa Administracja Skarbowa (KAS)",
        "tax_portal": "https://www.podatki.gov.pl",
        "tax_portal_name": "e-Urząd Skarbowy",
        "company_types": ["sp_z_oo", "sa", "jednoosobowa", "spolka_jawna"],
        "applicable_taxes": ["vat", "cit", "pit", "zus"],
        "tax_year": "calendar",
        "language": "pl",
    },
    "SE": {
        "name": "Sweden",
        "currency": "SEK",
        "vat_name": "Moms (Mervärdesskatt)",
        "vat_rates": {"standard": 25.0, "reduced": 12.0, "super_reduced": 6.0},
        "corporate_tax_rate": 20.6,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 12,
        "tax_authority": "Skatteverket",
        "tax_portal": "https://www.skatteverket.se",
        "tax_portal_name": "Skatteverket — Mina Sidor",
        "company_types": ["ab", "hb", "kb", "enskild_firma", "ef"],
        "applicable_taxes": ["moms", "bolagsskatt", "arbetsgivaravgifter"],
        "tax_year": "calendar",
        "language": "sv",
    },
    "AT": {
        "name": "Austria",
        "currency": "EUR",
        "vat_name": "Umsatzsteuer (USt)",
        "vat_rates": {"standard": 20.0, "reduced": 13.0, "super_reduced": 10.0},
        "corporate_tax_rate": 23.0,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 15,
        "tax_authority": "Bundesministerium für Finanzen (BMF)",
        "tax_portal": "https://finanzonline.bmf.gv.at",
        "tax_portal_name": "FinanzOnline",
        "company_types": ["gmbh", "ag", "og", "kg", "einzelunternehmen"],
        "applicable_taxes": [
            "umsatzsteuer",
            "koerperschaftsteuer",
            "einkommensteuer",
            "sozialversicherung",
        ],
        "tax_year": "calendar",
        "language": "de",
    },
    "CH": {
        "name": "Switzerland",
        "currency": "CHF",
        "vat_name": "MWST/TVA/IVA",
        "vat_rates": {"standard": 8.1, "reduced": 2.6, "accommodation": 3.8},
        "corporate_tax_rate": 14.9,
        "vat_filing": "quarterly",
        "vat_deadline_days": 60,
        "tax_authority": "Eidgenössische Steuerverwaltung (ESTV)",
        "tax_portal": "https://www.estv.admin.ch",
        "tax_portal_name": "ePortal ESTV",
        "company_types": ["ag", "gmbh", "einzelfirma", "kollektivgesellschaft"],
        "applicable_taxes": ["mwst", "gewinnsteuer", "kapitalsteuer", "quellensteuer"],
        "tax_year": "calendar",
        "language": "de_fr_it",
    },
    "PT": {
        "name": "Portugal",
        "currency": "EUR",
        "vat_name": "IVA (Imposto sobre o Valor Acrescentado)",
        "vat_rates": {"standard": 23.0, "intermediate": 13.0, "reduced": 6.0},
        "corporate_tax_rate": 21.0,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 20,
        "tax_authority": "Autoridade Tributária e Aduaneira (AT)",
        "tax_portal": "https://www.portaldasfinancas.gov.pt",
        "tax_portal_name": "Portal das Finanças",
        "company_types": ["lda", "sa", "eni", "sociedade_civil"],
        "applicable_taxes": ["iva", "irc", "irs", "seguranca_social"],
        "tax_year": "calendar",
        "language": "pt",
    },
    "DK": {
        "name": "Denmark",
        "currency": "DKK",
        "vat_name": "Moms",
        "vat_rates": {"standard": 25.0},
        "corporate_tax_rate": 22.0,
        "vat_filing": "quarterly",
        "vat_deadline_days": 40,
        "tax_authority": "Skattestyrelsen",
        "tax_portal": "https://skat.dk",
        "tax_portal_name": "TastSelv Erhverv",
        "company_types": ["aps", "as", "enkeltmandsvirksomhed", "interessentskab"],
        "applicable_taxes": ["moms", "selskabsskat", "am_bidrag", "atp"],
        "tax_year": "calendar",
        "language": "da",
    },
    "NO": {
        "name": "Norway",
        "currency": "NOK",
        "vat_name": "Merverdiavgift (MVA)",
        "vat_rates": {"standard": 25.0, "reduced": 15.0, "super_reduced": 12.0},
        "corporate_tax_rate": 22.0,
        "vat_filing": "bi_monthly",
        "vat_deadline_days": 35,
        "tax_authority": "Skatteetaten",
        "tax_portal": "https://www.altinn.no",
        "tax_portal_name": "Altinn",
        "company_types": ["as", "ans", "enkeltpersonforetak", "da"],
        "applicable_taxes": ["mva", "selskapsskatt", "arbeidsgiveravgift"],
        "tax_year": "calendar",
        "language": "no",
    },
    "FI": {
        "name": "Finland",
        "currency": "EUR",
        "vat_name": "ALV (Arvonlisävero)",
        "vat_rates": {"standard": 25.5, "reduced": 14.0, "super_reduced": 10.0},
        "corporate_tax_rate": 20.0,
        "vat_filing": "monthly",
        "vat_deadline_days": 12,
        "tax_authority": "Verohallinto (Vero)",
        "tax_portal": "https://www.vero.fi",
        "tax_portal_name": "OmaVero",
        "company_types": ["oy", "oyj", "ay", "ky", "tmi"],
        "applicable_taxes": ["alv", "yhteisovero", "tyonantajamaksut"],
        "tax_year": "calendar",
        "language": "fi",
    },
    "GR": {
        "name": "Greece",
        "currency": "EUR",
        "vat_name": "ΦΠΑ (Φόρος Προστιθέμενης Αξίας)",
        "vat_rates": {"standard": 24.0, "reduced": 13.0, "super_reduced": 6.0},
        "corporate_tax_rate": 22.0,
        "vat_filing": "monthly",
        "vat_deadline_days": 26,
        "tax_authority": "ΑΑΔΕ (Ανεξάρτητη Αρχή Δημοσίων Εσόδων)",
        "tax_portal": "https://www.aade.gr",
        "tax_portal_name": "myAADE",
        "company_types": ["ike", "ae", "epe", "oe", "ee"],
        "applicable_taxes": ["fpa", "forologhia_eisodimatos", "eisforeb_asfalisis"],
        "tax_year": "calendar",
        "language": "el",
    },
    "HU": {
        "name": "Hungary",
        "currency": "HUF",
        "vat_name": "ÁFA (Általános Forgalmi Adó)",
        "vat_rates": {"standard": 27.0, "reduced": 18.0, "super_reduced": 5.0},
        "corporate_tax_rate": 9.0,
        "vat_filing": "monthly",
        "vat_deadline_days": 20,
        "tax_authority": "Nemzeti Adó- és Vámhivatal (NAV)",
        "tax_portal": "https://nav.gov.hu",
        "tax_portal_name": "Ügyfélportál NAV",
        "company_types": ["kft", "zrt", "nyrt", "bt", "kkt", "egyeni_vallalkozo"],
        "applicable_taxes": ["afa", "tao", "szja", "tbjarul"],
        "tax_year": "calendar",
        "language": "hu",
    },
    "CZ": {
        "name": "Czech Republic",
        "currency": "CZK",
        "vat_name": "DPH (Daň z přidané hodnoty)",
        "vat_rates": {"standard": 21.0, "reduced": 15.0, "super_reduced": 10.0},
        "corporate_tax_rate": 21.0,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 25,
        "tax_authority": "Finanční správa",
        "tax_portal": "https://adisspr.mfcr.cz",
        "tax_portal_name": "Daňový portál",
        "company_types": ["sro", "as", "vos", "ks"],
        "applicable_taxes": ["dph", "dan_z_prijmu", "socialni_pojisteni", "zdravotni_pojisteni"],
        "tax_year": "calendar",
        "language": "cs",
    },
    "RO": {
        "name": "Romania",
        "currency": "RON",
        "vat_name": "TVA (Taxa pe Valoarea Adăugată)",
        "vat_rates": {"standard": 19.0, "reduced": 9.0, "super_reduced": 5.0},
        "corporate_tax_rate": 16.0,
        "vat_filing": "monthly_or_quarterly",
        "vat_deadline_days": 25,
        "tax_authority": "ANAF (Agenția Națională de Administrare Fiscală)",
        "tax_portal": "https://www.anaf.ro",
        "tax_portal_name": "Spațiul Privat Virtual (SPV)",
        "company_types": ["srl", "sa", "pfa", "ii", "if"],
        "applicable_taxes": ["tva", "impozit_profit", "impozit_venit", "contributii_sociale"],
        "tax_year": "calendar",
        "language": "ro",
    },
}


def get_country_data(country_code: str) -> dict | None:
    """Get tax data for a country. Returns None if unsupported."""
    return COUNTRY_TAX_DATA.get(country_code.upper())


def get_all_countries() -> list[dict]:
    """List of all supported countries for dropdowns."""
    return [
        {
            "code": code,
            "name": data["name"],
            "currency": data["currency"],
            "vat_name": data["vat_name"],
            "vat_rate": data["vat_rates"]["standard"],
        }
        for code, data in sorted(COUNTRY_TAX_DATA.items(), key=lambda x: x[1]["name"])
    ]


SUPPORTED_COUNTRY_CODES = list(COUNTRY_TAX_DATA.keys())
