'use client'
import { useEffect, useState } from 'react'
import { reports as api } from '@/lib/api'
import type { Report, ReportDetail } from '@/lib/api'
import { analytics } from '@/lib/analytics'
import {
  BarChart2, Download, Calendar, TrendingUp, TrendingDown,
  CheckCircle, Loader2, AlertCircle
} from 'lucide-react'

const DEMO_WS = '00000000-0000-0000-0002-000000000001'

// ── Markdown generation ───────────────────────────────────────────────────────
// Uses content_md directly when available (richest output).
// Falls back to structured generation from report fields.

function buildMarkdown(report: ReportDetail): string {
  if (report.content_md) return report.content_md

  const period = report.period_end
    ? `Week ending ${new Date(report.period_end).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`
    : new Date(report.created_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

  const lines: string[] = []
  lines.push(`# ${report.title}`)
  lines.push(``)
  lines.push(`**Report type:** ${report.report_type.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}  `)
  lines.push(`**Period:** ${period}  `)
  lines.push(`**Generated:** ${new Date(report.created_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`)
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  if (report.summary) {
    lines.push(`## Executive Summary`)
    lines.push(``)
    lines.push(report.summary)
    lines.push(``)
  }

  const kpiEntries = Object.entries(report.kpis ?? {})
  if (kpiEntries.length > 0) {
    lines.push(`## Key Performance Indicators`)
    lines.push(``)
    lines.push(`| Metric | Value | Change |`)
    lines.push(`|--------|-------|--------|`)
    for (const [key, val] of kpiEntries) {
      const label = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
      const value = typeof val === 'object' && val !== null
        ? String((val as Record<string, unknown>).value ?? '—')
        : String(val ?? '—')
      const delta = typeof val === 'object' && val !== null
        ? (val as Record<string, unknown>).delta as number | undefined
        : undefined
      const deltaStr = delta !== undefined ? `${delta >= 0 ? '+' : ''}${delta}%` : '—'
      lines.push(`| ${label} | ${value} | ${deltaStr} |`)
    }
    lines.push(``)
  }

  const sections = report.sections ?? []
  for (const s of sections) {
    lines.push(`## ${(s as Record<string, string>).title}`)
    lines.push(``)
    lines.push((s as Record<string, string>).content)
    lines.push(``)
  }

  lines.push(`---`)
  lines.push(``)
  lines.push(`## Assumptions & Confidence`)
  lines.push(``)
  lines.push(`- Trend data: **inferred** from niche intelligence engine`)
  lines.push(`- Audience estimates: **estimated** based on niche category`)
  lines.push(`- KPI deltas: **observed** from connected data sources or seeded demo data`)
  lines.push(`- Recommendations: **AI-generated** — review before acting`)
  lines.push(``)
  lines.push(`> *Generated by AI Growth OS · Self-hosted · Private*`)

  return lines.join('\n')
}

function triggerDownload(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ── Sub-components ────────────────────────────────────────────────────────────

function KPIChip({ label, value, delta }: { label: string; value: unknown; delta?: number }) {
  return (
    <div className="bg-gray-50 rounded-lg p-3">
      <p className="text-xs text-gray-400">{label}</p>
      <p className="text-lg font-bold text-gray-900 mt-0.5">
        {typeof value === 'object' && value !== null
          ? String((value as Record<string, unknown>).value ?? '—')
          : String(value ?? '—')}
      </p>
      {delta !== undefined && (
        <p className={`text-xs flex items-center gap-1 mt-0.5 ${delta >= 0 ? 'text-green-600' : 'text-red-500'}`}>
          {delta >= 0 ? <TrendingUp size={10} /> : <TrendingDown size={10} />}
          {delta >= 0 ? '+' : ''}{delta}%
        </p>
      )}
    </div>
  )
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default function ReportsPage() {
  const [reportList, setReportList] = useState<Report[]>([])
  const [selected, setSelected] = useState<ReportDetail | null>(null)
  const [listLoading, setListLoading] = useState(true)
  const [detailLoading, setDetailLoading] = useState(false)
  const [exporting, setExporting] = useState(false)
  const [exported, setExported] = useState(false)
  const [exportError, setExportError] = useState('')

  // Load report list on mount
  useEffect(() => {
    api.list(DEMO_WS)
      .then(r => {
        setReportList(r.items)
        if (r.items.length > 0) loadDetail(r.items[0].id)
      })
      .catch(() => {})
      .finally(() => setListLoading(false))
  }, [])

  // Fetch full ReportDetail (includes sections + content_md) on selection
  async function loadDetail(reportId: string) {
    setDetailLoading(true)
    setSelected(null)
    try {
      const detail = await api.get(reportId)
      setSelected(detail)
    } catch {
      // If detail fetch fails, try to use list data cast as detail
      const fallback = reportList.find(r => r.id === reportId)
      if (fallback) setSelected(fallback as unknown as ReportDetail)
    } finally {
      setDetailLoading(false)
    }
  }

  async function handleExport() {
    if (!selected || exporting) return
    setExporting(true)
    setExportError('')
    try {
      // Re-fetch detail to ensure content_md is present
      let detail = selected
      if (!detail.content_md && !detail.sections?.length) {
        detail = await api.get(selected.id)
      }
      const md = buildMarkdown(detail)
      const slug = detail.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      triggerDownload(md, `${slug}-${new Date().toISOString().slice(0, 10)}.md`)
      analytics.reportExported(detail.report_type, detail.id)
      setExported(true)
      setTimeout(() => setExported(false), 2500)
    } catch {
      setExportError('Export failed. Try again.')
      setTimeout(() => setExportError(''), 3000)
    } finally {
      setExporting(false)
    }
  }

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-gray-900">Reports</h1>
          <p className="text-sm text-gray-500">Growth summaries, opportunities, and risks</p>
        </div>
      </div>

      <div className="flex gap-6">
        {/* Report list */}
        <div className="w-72 flex-shrink-0 space-y-2">
          {listLoading ? (
            <div className="space-y-2">{[1, 2].map(i => <div key={i} className="h-16 card animate-pulse" />)}</div>
          ) : reportList.length === 0 ? (
            <div className="card p-6 text-center">
              <BarChart2 size={24} className="mx-auto text-gray-200 mb-2" />
              <p className="text-xs text-gray-400">No reports yet</p>
            </div>
          ) : reportList.map(report => (
            <button
              key={report.id}
              onClick={() => loadDetail(report.id)}
              className={`w-full text-left card p-4 hover:border-brand-300 transition-colors ${selected?.id === report.id ? 'border-brand-400 bg-brand-50' : ''}`}
            >
              <div className="flex items-center gap-2 mb-1">
                <span className="badge-blue text-xs">{report.report_type.replace(/_/g, ' ')}</span>
              </div>
              <p className="text-sm font-medium text-gray-900 truncate">{report.title}</p>
              <p className="text-xs text-gray-400 mt-0.5 flex items-center gap-1">
                <Calendar size={10} />
                {report.period_end
                  ? new Date(report.period_end).toLocaleDateString()
                  : new Date(report.created_at).toLocaleDateString()}
              </p>
            </button>
          ))}
        </div>

        {/* Detail panel */}
        {detailLoading ? (
          <div className="flex-1 card p-12 flex items-center justify-center gap-2 text-gray-400 text-sm">
            <Loader2 size={16} className="animate-spin" /> Loading report…
          </div>
        ) : selected ? (
          <div className="flex-1 card p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-semibold text-gray-900">{selected.title}</h2>
              <div className="flex items-center gap-2">
                {exportError && (
                  <span className="text-xs text-red-500 flex items-center gap-1">
                    <AlertCircle size={11} /> {exportError}
                  </span>
                )}
                <button
                  onClick={handleExport}
                  disabled={exporting}
                  className="btn-secondary flex items-center gap-1 text-xs"
                >
                  {exporting
                    ? <><Loader2 size={12} className="animate-spin" /> Exporting…</>
                    : exported
                    ? <><CheckCircle size={12} className="text-emerald-500" /> Exported!</>
                    : <><Download size={12} /> Export MD</>}
                </button>
              </div>
            </div>

            {selected.summary && (
              <div className="bg-gray-50 rounded-lg p-4 mb-5">
                <p className="text-sm text-gray-700 leading-relaxed">{selected.summary}</p>
              </div>
            )}

            {/* KPIs */}
            {Object.keys(selected.kpis ?? {}).length > 0 && (
              <div className="mb-5">
                <h3 className="text-sm font-medium text-gray-700 mb-3">Key Performance Indicators</h3>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  {Object.entries(selected.kpis).map(([k, v]) => (
                    <KPIChip
                      key={k}
                      label={k.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}
                      value={v}
                      delta={typeof v === 'object' && v !== null ? (v as Record<string, unknown>).delta as number | undefined : undefined}
                    />
                  ))}
                </div>
              </div>
            )}

            {/* Content MD preview (if available) */}
            {selected.content_md && (selected.sections ?? []).length === 0 && (
              <div className="border-t border-gray-50 pt-4">
                <pre className="text-xs text-gray-500 whitespace-pre-wrap font-sans leading-relaxed max-h-64 overflow-y-auto">
                  {selected.content_md.slice(0, 800)}{selected.content_md.length > 800 ? '\n\n…(full report in exported .md file)' : ''}
                </pre>
              </div>
            )}

            {/* Sections */}
            {(selected.sections ?? []).length > 0 && (
              <div className="space-y-5">
                {(selected.sections as Record<string, string>[]).map((s, i) => (
                  <div key={i} className="border-t border-gray-50 pt-4">
                    <h3 className="text-sm font-semibold text-gray-800 mb-2">{s.title}</h3>
                    <p className="text-sm text-gray-600 leading-relaxed">{s.content}</p>
                  </div>
                ))}
              </div>
            )}

            {/* Provenance footer */}
            <div className="mt-6 pt-4 border-t border-gray-100 flex flex-wrap gap-2">
              {[
                { label: 'Trend data', source: 'inferred', cls: 'bg-blue-50 text-blue-600 border-blue-100' },
                { label: 'Audience estimates', source: 'estimated', cls: 'bg-amber-50 text-amber-600 border-amber-100' },
                { label: 'Recommendations', source: 'AI-generated', cls: 'bg-violet-50 text-violet-600 border-violet-100' },
              ].map(({ label, source, cls }) => (
                <span key={label} className={`text-[10px] px-2 py-0.5 rounded-full border ${cls} font-medium`}>
                  {label}: {source}
                </span>
              ))}
            </div>
          </div>
        ) : (
          <div className="flex-1 card p-12 text-center">
            <BarChart2 size={36} className="mx-auto text-gray-200 mb-3" />
            <p className="text-gray-400 text-sm">Select a report to view details</p>
          </div>
        )}
      </div>
    </div>
  )
}
